Finanzas/Controllers/CuentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Finanzas.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Finanzas.Controllers
{
    [Authorize]
    public class CuentaController : Controller
    {
        private readonly ContextoFinanzas context;
        public CuentaController(ContextoFinanzas context)
        {
            this.context = context;
        }

        [HttpGet]
        public ActionResult Index()
        {
            var cuentas = context.Cuentas
                .Include(o => o.Categoria)
                .Where(o => o.IdUser == LoggedUser().Id)
                .ToList();
            ViewBag.Total = cuentas.Sum(o => o.Saldo);
            return View("Index", cuentas);
        }

        [HttpGet]
        public ActionResult Registrar()
        {
            ViewBag.Categorias = context.Categorias
                .ToList();
            return View("Registrar", new Cuenta());
        }

        [HttpPost]
        public ActionResult Registrar(Cuenta cuenta)
        {
            if (ModelState.IsValid)
            {
                if(cuenta.IdCategoria == 2)
                {
                    cuenta.Limite = cuenta.Saldo;
                    cuenta.Saldo = 0;
                }else if(cuenta.Saldo > 0)
                {
                    cuenta.Limite = 0;
                    cuenta.Transaccions = new List<Transaccion>
                    {
                        new Transaccion
                        {
                            Fecha = DateTime.Now,
                            Tipo = "Ingreso",
                            Monto = cuenta.Saldo,
                            Descripcion = "Monto Inicial"
                        }
                    };
                }
                cuenta.IdUser = LoggedUser().Id;
                context.Cuentas.Add(cuenta);
                context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Categorias = context.Categorias
            .ToList();
            return View("Registrar", cuenta);
        }

        protected User LoggedUser()
        {
            var claim = HttpContext.User.Claims.FirstOrDefault();
            var user = context.Users.Where(o => o.Username == claim.Value).FirstOrDefault();
            return user;
        }
    }
}

Finanzas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Finanzas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Finanzas</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item active">
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link" href="/User/Login">Login</a>
                            }
                            else
                            {
                                <a class="nav-link" href="#">@User.Identity.Name</a>
                            }
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item active">
                                <a class="nav-link" href="/user/logout">Logout</a>
                            </li>
                        }
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cuenta" asp-action="Index">Cuentas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Finanzas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    @RenderSection("Scripts", required: false)

</body>
</html>